name: ARCHE-Ingest

on:
  workflow_dispatch

jobs:
  build_pages:
    name: Ingest Data into ARCHE
    runs-on: ubuntu-latest
    env:
      MY_GITHUB_TOKEN: ${{secrets.MY_GITHUB_TOKEN}}
      ANT_OPTS: -Xmx5g
      TESTRUN: HANSI4EVER
    steps:
    - name: Perform Checkout
      uses: actions/checkout@v2
    - name: Install Saxon and Ant
      run: |
        apt-get update && apt-get install openjdk-11-jre-headless ant -y --no-install-recommend
        ./dl_saxon.sh
    - name: fetch data
      run: |
        ./fetch_data.sh
    - name: Build
      run: |
        ant -f build_arche.xml
    - name: ingestion dependencies
      run: |
        composer require "acdh-oeaw/arche-ingest:^1"
    - name: ingest ARCHE-CONSTANTS
      run: |
        vendor/bin/arche-import-metadata html/arche-constants.rdf https://arche-dev.acdh-dev.oeaw.ac.at/api ${{secrets.ARCHE_LOGIN}} ${{secrets.ARCHE_PASSWORD}}--retriesOnConflict 25
    - name: ingest msdesc resources and facs-cols
      run: |
        vendor/bin/arche-import-metadata html/arche.rdf https://arche-dev.acdh-dev.oeaw.ac.at/api ${{secrets.ARCHE_LOGIN}} ${{secrets.ARCHE_PASSWORD}}--retriesOnConflict 25
    - name: ingest facs-res
      run: |
        vendor/bin/arche-import-metadata html/arche-facs.rdf https://arche-dev.acdh-dev.oeaw.ac.at/api ${{secrets.ARCHE_LOGIN}} ${{secrets.ARCHE_PASSWORD}}--retriesOnConflict 25
    - name: Copy XML Files to to_ingest 
      run: |
        mkdir $PWD/to_ingest
        find -path "./data/editions/*.xml" -exec cp -prv '{}' './to_ingest' ';'
    - name: install repo-file-checker
      run: |
        composer require "acdh-oeaw/repo-file-checker:^2"
        mkdir -p filechecker/tmp filechecker/reports
    - name: run repo-file-checker
      run: |
        php -f vendor/acdh-oeaw/repo-file-checker/index.php -- --tmpDir filechecker/tmp --reportDir filechecker/reports to_ingest 0
    - name: ingest binaries
      run: |
        vendor/bin/arche-import-binary to_ingest https://id.acdh.oeaw.ac.at/pez-nachlass https://arche-dev.acdh-dev.oeaw.ac.at/api ${{secrets.ARCHE_LOGIN}} ${{secrets.ARCHE_PASSWORD}} --skip not_exist
